# Generated by Django 5.2.4 on 2025-07-24 14:31

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='task',
            name='share_with',
            field=models.ManyToManyField(
                blank=True,
                related_name='shared_tasks',
                to=settings.AUTH_USER_MODEL
            ),
        ),
    ]
